#!/usr/bin/env python3
"""secret santa command line tool for admin"""

import sys

from secretsanta import db
from secretsanta.models import User
from secretsanta.config import Config


def print_menu():
    print(MENU)

def do_reset_child():
    print()
    print('NOT IMPLEMENTED')

def reset_password(username, password):
    print("\nsetting password for user %s to %s" % (username, password))
    user = User.query.filter_by(username=username).first()
    if user:
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        print("password successfully set")
    else:
        print('username %s not found' % username )

def do_reset_user_password():
    print()
    username = input("Enter user name: ")
    password = input('Enter Password: ')
    password2 = input('Enter Password again: ')
    if password == password2:
        reset_password(username, password)
    else:
        print("Passwords do not match.  Try Again")
    input("Press Enter to continue")

def do_quit():
    print("Bye! Bye!")
    sys.exit()

MENU = """
(C) Reset Child
(P) Reset Password
(Q) Quit
"""

ACTIONS = {
    'C': do_reset_child,
    'P': do_reset_user_password,
    'Q': do_quit
}

def main():
    while True:
        print_menu()
        choice = input("Enter your Choice: ")
        try:
            ACTIONS[choice]()
        except KeyError:
            continue
 
if __name__ == '__main__':
    main()