#!/usr/bin/env python
"""secret santa command line tool to post to mattermost"""
import argparse
import json
import ssl
import urllib2

MMHOST = ""
WEBHOOK = ""
WEBSERVER = ""
CHANNEL = ""

def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("--mention", help="which user to tag in the message")
    parser.add_argument("--message", help=("The message you want to pass along"
                                         "use double quotes for multi line"))
    args = parser.parse_args()
    return args.mention, args.message

def post_to_mattermost(channel, message):
    payload = {
        "username": "SecretSanta",
        "icon": WEBSERVER + "/static/santahat.jpg",
        "channel": channel,
        "text": message,
    }
    print payload
    mm_request = urllib2.Request(MMHOST + WEBHOOK, json.dumps(payload),
                                 {'Content-Type':'application/json'})
    context = ssl._create_unverified_context()
    response = urllib2.urlopen(mm_request, context=context)
    result = response.read()
    print result

def main():
    mention, message = parse_arguments()
    message = "Hi @{0},\n\n{1}".format(mention, message)
    post_to_mattermost(CHANNEL, message)
    print "posted to mattermost channel {0}".format(channel)

if __name__ == '__main__':
    main()
